mysite/blog/urls.py
from django.conf.urls import url
from . import views
from .feeds import LatestPostsFeed

urlpatterns = [
	#WIDOKI POSTA
	url(r'^$', views.post_list, name='post_list'), 
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list, name='post_list_by_tag'),
	# url(r'^$', views.PostListView.as_view(), name='post_list'),
	url(r'^(?P<post_id>\d+)/share/$', views.post_share,
               name='post_share'),
	url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/'
               r'(?P<post>[-\w]+)/$',
               views.post_detail,
               name='post_detail'),
	url(r'^feed/$', LatestPostsFeed(), name='post_feed'),
	url(r'^search/$', views.post_search, name='post_search'),
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap


sitemaps = {
	'posts': PostSitemap,
}

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls',namespace='blog',app_name='blog')),
	url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
]

mysite/blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from taggit.managers import TaggableManager
# Create your models here.

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

class PublishedManager(models.Manager):
	def get_queryset(self):
		return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
   STATUS_CHOICES = (
       ('draft', 'Roboczy'),
       ('published', 'Opublikowany'),
   )
   title = models.CharField(max_length=250)
   slug = models.SlugField(max_length=250, unique_for_date='publish')
   author = models.ForeignKey(User, related_name='blog_posts')
   body = models.TextField()
   publish = models.DateTimeField(default=timezone.now)
   created = models.DateTimeField(auto_now_add=True)
   updated = models.DateTimeField(auto_now=True)
   status = models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')

   objects = models.Manager()
   published = PublishedManager()


   class Meta:
       ordering = ('-publish',)
   def __str__(self):
       return self.title

   def get_absolute_url(self):
	   return reverse('blog:post_detail',
	                  args=[self.publish.year,
	                        self.publish.strftime('%m'),
	                        self.publish.strftime('%d'),
	                        self.slug])
   tags = TaggableManager()
    


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments')#WIELE COMENTARZY DO POSTU
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    # rate = models.TextField()

    class Meta:
        ordering = ('created',)
	def __str__(self):
		return 'Komentarz dodany przez {} dla posta {}'.format(self.name, self.post)

mysite/blog/forms.py
from django import forms
from .models import Comment

class NewPost(forms.Form):
   title = forms.CharField(max_length=100)
   name = forms.CharField(max_length=25)
   body = forms.CharField(required=False, max_length=200)

class EmailPostForm(forms.Form):
   name = forms.CharField(max_length=25)
   email = forms.EmailField()
   to = forms.EmailField()
   comments = forms.CharField(required=False,widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

class SearchForm(forms.Form):
	query = forms.CharField()

mysite/blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count
from .models import Post, Comment
from .forms import EmailPostForm, CommentForm

from .forms import EmailPostForm, CommentForm, SearchForm 
from haystack.query import SearchQuerySet

def post_list(request, tag_slug = None):
	object_list = Post.published.all()
	tag = None

	if tag_slug:
		print("in tag slug")
		tag= get_object_or_404(Tag, slug = tag_slug)
		object_list = object_list.filter(tags__in = [tag])
	else:
		print("not in tag slug")

	paginator = Paginator(object_list, 3) # Trzy posty na każdej stronie. 
	page = request.GET.get('page')
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		# Jeżeli zmienna page nie jest liczbą całkowitą, wówczas pobierana jest pierwsza strona wyników.
		posts = paginator.page(1) 
	except EmptyPage:
		# Jeżeli zmienna page ma wartość większą niż numer ostatniej strony wyników, wtedy pobierana # jest ostatnia strona wyników.
		posts = paginator.page(paginator.num_pages)
	return render(request, 'blog/post/list.html', {'page': page, 'posts': posts,'tag': tag})

def post_share(request, post_id):
	# Pobranie posta na podstawie jego identyfikatora.
	post = get_object_or_404(Post, id=post_id, status='published')
	sent = False
	if request.method == 'POST':
    # Formularz został wysłany.
		form = EmailPostForm(request.POST)
		if form.is_valid():
			# Weryfikacja pól formularza zakończyła się powodzeniem...
			cleaned_form = form.cleaned_data
			post_url = request.build_absolute_uri(post.get_absolute_url())
			subject = '{} ({}) zachęca do przeczytania "{}"'.format(cleaned_form['name'],['email'], post.title)
			message = 'Przeczytaj post "{}" na stronie {}\n\n Komentarz dodany przez {}: {}'.format(post.title, post_url, cleaned_form['name'], cleaned_form['comments']) 
			print("halekco")
			send_mail(subject, message, 'rafald121@mgmail.com', [cleaned_form['to']])
			sent = True
			# ... więc można wysłać wiadomość e-mail.
	else:
		form = EmailPostForm()
	return render(request, 'blog/post/share.html', {'post': post,'form': form,'sent': sent})


class PostListView(ListView):
	queryset = Post.published.all()
	context_object_name = 'posts'
	paginate_by = 1
	template_name = 'blog/post/list.html'

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                                  status='published',
                                  publish__year=year,
                                  publish__month=month,
                                  publish__day=day)
    comments = post.comments.filter(active=True)

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
			# Utworzenie obiektu Comment, ale jeszcze nie zapisujemy go w bazie danych.
            new_comment = comment_form.save(commit=False)
			# Przypisanie komentarza do bieżącego posta.
            new_comment.post = post
            # Zapisanie komentarza w bazie danych.
            new_comment.save()
    else:
    	comment_form = CommentForm()
	# Lista podobnych postów.
	post_tags_ids = post.tags.values_list('id', flat=True)
	similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
	similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]
    return render(request, 'blog/post/detail.html',{'post': post, 'comments':comments, 'comment_form': comment_form, 'similar_posts': similar_posts} )


def post_search(request):
	form = SearchForm()
	if 'query' in request.GET:
		form = SearchForm(request.GET)
		if form.is_valid():
			cd = form.cleaned_data
			results = SearchQuerySet().models(Post).filter(content=cd['query']).load_all()
			# Obliczenie całkowitej liczby wyników.
			total_results = results.count()
			return render(request,'blog/post/search.html',{'form': form,'cd': cd,'results': results,'total_results': total_results})
	else:
	   return render(request,	'blog/post/search.html',	{'form': form})




# Create your views here.

mysite/blog/templates/blog/base.html
{% load blog_tags %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
   <title>{% block title %}{% endblock %}</title>
   <link href="{% static "css/blog.css" %}" rel="stylesheet">
  </head>
  <body>
   <div id="content">
     {% block content %}
     {% endblock %}
   </div>
   <div id="sidebar">
     <!-- <h2>Mój blog</h2> -->
     <h2><a href="{% url "blog:post_list" %}">Mój blog</a></h2>
      <p>To jest mój blog. Dotychczas opublikowałem {% wszystkie_posty %} postów.</p>
      <p><a href="{% url "blog:post_feed" %}">Subskrybuj kanał RSS</a></p>
      <h3>Najnowsze posty</h3>
      {% show_latest_posts 3 %}


      <h3>Najczęściej komentowane posty</h3>
       {% get_most_commented_posts as most_commented_posts %}
       <ul>
       {% for post in most_commented_posts %}
         <li>
           <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
         </li>
       {% endfor %}
       </ul>
   </div>
  </body>
</html>

mysite/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}
{% block content %}



 <h1>{{ post.title }}</h1>
 <p class="date">
   Opublikowany {{ post.publish }} przez {{ post.author }}
 </p>
 {{ post.body|markdown }}
	<p>
	 <a href="{% url "blog:post_share" post.id %}">
	   Udostępnij post
	 </a>
	</p>

 <p class="tags">
	     Tagi w detailsach:
	     {% for tag in post.tags.all %}
	       <a href="{% url "blog:post_list_by_tag" tag.slug %}">
	         {{ tag.name }}
	       </a>
	       {% if not forloop.last %}
	       	,
	       {% endif %}
	     {% endfor %}
	</p>




  <h2>Podobne posty</h2>
       {% for post in similar_posts %}
         <p>
           <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
		 </p>
	       {% empty %}
	         Nie ma podobnych postów.
       {% endfor %}

{% with comments.count as total_comments %}
	<h2>{{ total_comments }} komentarz{{ total_comments|pluralize:"y" }} </h2>
{% endwith %}
		{% for comment in comments %}
         <div class="comment">
            <p class="info">
              Komentarz {{ forloop.counter }} dodany przez {{ comment.name }}
              {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
         </div>
        {% empty %}
         <p>Nie ma jeszcze żadnych komentarzy.</p>
		{% endfor %}

	  {% if new_comment %}
         <h2>Twój komentarz został dodany.</h2>
       {% else %}
         <h2>Dodaj nowy komentarz</h2>
         <form action="." method="post">
           {{ comment_form.as_p }}
           {% csrf_token %}
           <p><input type="submit" value="Dodaj komentarz"></p>
         </form>
       {% endif %}
{% endblock %}

mysite/blog/templates/blog/post/latest_posts.html
<ul>
{% for post in latest_posts %}
 <li>
   <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
 </li>
{% endfor %}
</ul>

mysite/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% load blog_tags %}


{% block title %}Mój blog{% endblock %}

{% block content %}
 <h1>Mój blog</h1>

{% if tag %}
	 <h2>Posty oznaczone tagiem "{{ tag.name }}"</h2>
{% endif %}




 {% for post in posts %}
   <h2>
     <a href="{{ post.get_absolute_url }}">
       {{ post.title }}
     </a>
      <p class="tags">
	     Tagiiii:
	     {% for tag in post.tags.all %}
	       <a href="{% url "blog:post_list_by_tag" tag.slug %}">
	         {{ tag.name }}
	       </a>
	       {% if not forloop.last %}
	       	,
	       {% endif %}
	     {% endfor %}
	</p>


   </h2>
   <p class="date">
     Opublikowany {{ post.publish }} przez {{ post.author }}
   </p>
   <!-- {{ post.body|truncatewords:30|linebreaks }} -->
   {{ post.body|markdown|truncatewords_html:30 }}


 {% endfor %}
 <!-- {% include "blog/post/pagination.html" with page=page_obj %} -->
 {% include "blog/post/pagination.html" with page=posts %}

{% endblock %}

mysite/blog/templates/blog/post/pagination.html
<div class="pagination">
     <span class="step-links">
		{% if page.has_previous %}
			<a href="?page={{ page.previous_page_number }}">Poprzednia</a>
        {% endif %}
        <span class="current">
            Strona {{ page.number }} z {{ page.paginator.num_pages }}.
       	</span>
        {% if page.has_next %}
           <a href="?page={{ page.next_page_number }}">Następna</a>
        {% endif %}
     </span>
</div>

mysite/blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% block title %}Szukaj{% endblock %}
{% block content %}
 {% if "query" in request.GET %}
  <h1>Posty zawierające "{{ cd.query }}"</h1>
  <h3>Znaleziono {{ total_results }} wynik{{ total_results|pluralize:"i" }}</h3> 
  {% for result in results %}
    {% with post=result.object %}
      <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4> 
      {{ post.body|truncatewords:5 }}
    {% endwith %}
  {% empty %}
    <p>Brak wyników dla podanego zapytania.</p>
  {% endfor %}
  <p><a href="{% url "blog:post_search" %}">Szukaj ponownie</a></p>
 {% else %}
   <h1>Szukaj postów</h1>
   <form action="." method="get">
     {{ form.as_p }}
     <input type="submit" value="Szukaj">
   </form>
 {% endif %}
{% endblock %}

mysite/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}Udostępnij post{% endblock %}
{% block content %}
 {% if sent %}
    <h1>Wiadomość e-mail została wysłana</h1>
    <p>
      Wysłanie posta "{{ post.title }}" do {{ cd.to }} zakończyło się sukcesem. 
    </p>
 {% else %}
    <h1>Udostępnij "{{ post.title }}" przez e-mail</h1>
    <form action="." method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" value="Wyślij wiadomość e-mail">
    </form>
 {% endif %}
{% endblock %}